// to post a blog
export const POST_A_BLOG_START = "POST_A_BLOG_START";
export const POST_A_BLOG_SUCCESS = "POST_A_BLOG_SUCCESS";
export const POST_A_BLOG_ERROR = "POST_A_BLOG_ERROR";

// get a particular post data
export const GET_POST_DATA_START = "GET_POST_DATA_START";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_ERROR = "GET_POST_DATA_ERROR";

// TO UPDATE A BLOG
export const UPDATE_A_BLOG_START = "UPDATE_A_BLOG_START";
export const UPDATE_A_BLOG_SUCCESS = "UPDATE_A_BLOG_SUCCESS";
export const UPDATE_A_BLOG_ERROR = "UPDATE_A_BLOG_ERROR";

// TO DELETE A BLOG
export const DELETE_A_BLOG_START = "DELETE_A_BLOG_START";
export const DELETE_A_BLOG_SUCCESS = "DELETE_A_BLOG_SUCCESS";
export const DELETE_A_BLOG_ERROR = "DELETE_A_BLOG_ERROR";
