// to post a blog
export const POST_A_BLOG_START = "POST_A_BLOG_START";
export const POST_A_BLOG_SUCCESS = "POST_A_BLOG_SUCCESS";
export const POST_A_BLOG_ERROR = "POST_A_BLOG_ERROR";

// TO UPDATE A BLOG
export const UPDATE_A_BLOG_START = "UPDATE_A_BLOG_START";
export const UPDATE_A_BLOG_SUCCESS = "UPDATE_A_BLOG_SUCCESS";
export const UPDATE_A_BLOG_ERROR = "UPDATE_A_BLOG_ERROR";

// TO DELETE A BLOG
export const DELETE_A_BLOG_START = "DELETE_A_BLOG_START";
export const DELETE_A_BLOG_SUCCESS = "DELETE_A_BLOG_SUCCESS";
export const DELETE_A_BLOG_ERROR = "DELETE_A_BLOG_ERROR";

// get a particular post data
export const GET_POST_DATA_START = "GET_POST_DATA_START";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_ERROR = "GET_POST_DATA_ERROR";

//get all post data
export const GET_ALL_POST_DATA_START = "GET_ALL_POST_DATA_START";
export const GET_ALL_POST_DATA_SUCCESS = "GET_ALL_POST_DATA_SUCCESS";
export const GET_ALL_POST_DATA_ERROR = "GET_ALL_POST_DATA_ERROR";

// to like a post
export const LIKE_POST_START = "LIKE_POST_START";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";

// to unlike a post
export const UNLIKE_POST_START = "UNLIKE_POST_START";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_ERROR = "UNLIKE_POST_ERROR";

// to save a post
export const SAVE_POST_START = "SAVE_POST_START";
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";
export const SAVE_POST_ERROR = "SAVE_POST_ERROR";

// to unsaved a post
export const UNSAVE_POST_START = "UNSAVE_POST_START";
export const UNSAVE_POST_SUCCESS = "UNSAVE_POST_SUCCESS";
export const UNSAVE_POST_ERROR = "UNSAVE_POST_ERROR";

// post a comment
export const POST_A_COMMENT_START = "POST_A_COMMENT_START";
export const POST_A_COMMENT_SUCCESS = "POST_A_COMMENT_SUCCESS";
export const POST_A_COMMENT_ERROR = "POST_A_COMMENT_ERROR";

// DELETE a comment
export const DELETE_A_COMMENT_START = "DELETE_A_COMMENT_START";
export const DELETE_A_COMMENT_ERROR = "DELETE_A_COMMENT_ERROR";
