// FOR CREATING USER ACCOUNT--
export const CREATE_USER_ACCOUNT_START = "CREATE_USER_ACCOUNT_START";
export const CREATE_USER_ACCOUNT_SUCCESS = "CREATE_USER_ACCOUNT_SUCCESS";
export const CREATE_USER_ACCOUNT_ERROR = "CREATE_USER_ACCOUNT_ERROR";

// for authorisation
export const VERIFY_USER_AUTH_START = "VERIFY_USER_AUTH_START";
export const VERIFY_USER_AUTH_SUCCESS = "VERIFY_USER_AUTH_SUCCESS";
export const VERIFY_USER_AUTH_ERROR = "VERIFY_USER_AUTH_ERROR";

// authorised or not
export const AUTHORISED = "AUTHORISED";
export const NOT_AUTHORISED = "NOT_AUTHORISED";

// for login
export const LOGIN_USER_ACCOUNT_START = "LOGIN_USER_ACCOUNT_START";
export const LOGIN_USER_ACCOUNT_SUCCESS = "LOGIN_USER_ACCOUNT_SUCCESS";
export const LOGIN_USER_ACCOUNT_ERROR = "LOGIN_USER_ACCOUNT_ERROR";

// for edit or update
export const EDIT_USER_ACCOUNT_START = "EDIT_USER_ACCOUNT_START";
export const EDIT_USER_ACCOUNT_SUCCESS = "EDIT_USER_ACCOUNT_SUCCESS";
export const EDIT_USER_ACCOUNT_ERROR = "EDIT_USER_ACCOUNT_ERROR";

// for add user email
export const ADD_USER_EMAIL_START = "ADD_USER_EMAIL_START";
export const ADD_USER_EMAIL_SUCCESS = "ADD_USER_EMAIL_SUCCESS";
export const ADD_USER_EMAIL_ERROR = "ADD_USER_EMAIL_ERROR";
