// FOR CREATING USER ACCOUNT--
export const CREATE_USER_ACCOUNT_START = "CREATE_USER_ACCOUNT_START";
export const CREATE_USER_ACCOUNT_SUCCESS = "CREATE_USER_ACCOUNT_SUCCESS";
export const CREATE_USER_ACCOUNT_ERROR = "CREATE_USER_ACCOUNT_ERROR";

// for authorisation
export const VERIFY_USER_AUTH_START = "VERIFY_USER_AUTH_START";
export const VERIFY_USER_AUTH_SUCCESS = "VERIFY_USER_AUTH_SUCCESS";
export const VERIFY_USER_AUTH_ERROR = "VERIFY_USER_AUTH_ERROR";

// authorised or not
export const AUTHORISED = "AUTHORISED";
export const NOT_AUTHORISED = "NOT_AUTHORISED";

// for login
export const LOGIN_USER_ACCOUNT_START = "LOGIN_USER_ACCOUNT_START";
export const LOGIN_USER_ACCOUNT_SUCCESS = "LOGIN_USER_ACCOUNT_SUCCESS";
export const LOGIN_USER_ACCOUNT_ERROR = "LOGIN_USER_ACCOUNT_ERROR";

// for edit or update
export const EDIT_USER_ACCOUNT_START = "EDIT_USER_ACCOUNT_START";
export const EDIT_USER_ACCOUNT_SUCCESS = "EDIT_USER_ACCOUNT_SUCCESS";
export const EDIT_USER_ACCOUNT_ERROR = "EDIT_USER_ACCOUNT_ERROR";

// for add user email
export const ADD_USER_EMAIL_START = "ADD_USER_EMAIL_START";
export const ADD_USER_EMAIL_SUCCESS = "ADD_USER_EMAIL_SUCCESS";
export const ADD_USER_EMAIL_ERROR = "ADD_USER_EMAIL_ERROR";
// for remove user email
export const REMOVE_USER_EMAIL_START = "REMOVE_USER_EMAIL_START";
export const REMOVE_USER_EMAIL_SUCCESS = "REMOVE_USER_EMAIL_SUCCESS";
export const REMOVE_USER_EMAIL_ERROR = "REMOVE_USER_EMAIL_ERROR";

// for changing password
export const CHANGE_PASSWORD_START = "CHANGE_PASSWORD_START";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

// for changing password if user forget!!
export const FORGET_CHANGE_PASSWORD_START = "FORGET_CHANGE_PASSWORD_START";
export const FORGET_CHANGE_PASSWORD_SUCCESS = "FORGET_CHANGE_PASSWORD_SUCCESS";
export const FORGET_CHANGE_PASSWORD_ERROR = "FORGET_CHANGE_PASSWORD_ERROR";

// for deleting user account!!
export const CHECK_PASSWORD_FOR_DELETE_ACCOUNT_START =
  "CHECK_PASSWORD_FOR_DELETE_ACCOUNT_START";
export const CHECK_PASSWORD_FOR_DELETE_ACCOUNT_SUCCESS =
  "CHECK_PASSWORD_FOR_DELETE_ACCOUNT_SUCCESS";
export const CHECK_PASSWORD_FOR_DELETE_ACCOUNT_ERROR =
  "CHECK_PASSWORD_FOR_DELETE_ACCOUNT_ERROR";

// for deleting user account!!
export const DELETE_USER_ACCOUNT_START = "DELETE_USER_ACCOUNT_START";
export const DELETE_USER_ACCOUNT_SUCCESS = "DELETE_USER_ACCOUNT_SUCCESS";
export const DELETE_USER_ACCOUNT_ERROR = "DELETE_USER_ACCOUNT_ERROR";

// get Blogger data!!
export const GET_BLOGGER_DATA_START = "GET_BLOGGER_DATA_START";
export const GET_BLOGGER_DATA_SUCCESS = "GET_BLOGGER_DATA_SUCCESS";
export const GET_BLOGGER_DATA_ERROR = "GET_BLOGGER_DATA_ERROR";

// to follow a blogger!
export const FOLLOW_BLOGGER_START = "FOLLOW_BLOGGER_START";
export const FOLLOW_BLOGGER_ERROR = "FOLLOW_BLOGGER_ERROR";

// to unfollow a blogger!
export const UNFOLLOW_BLOGGER_START = "UNFOLLOW_BLOGGER_START";
export const UNFOLLOW_BLOGGER_ERROR = "UNFOLLOW_BLOGGER_ERROR";
