// FOR CREATING USER ACCOUNT--
export const CREATE_USER_ACCOUNT_START = 'CREATE_USER_ACCOUNT_START';
export const CREATE_USER_ACCOUNT_SUCCESS = 'CREATE_USER_ACCOUNT_SUCCESS';
export const CREATE_USER_ACCOUNT_ERROR = 'CREATE_USER_ACCOUNT_ERROR';

// for authorisation
export const VERIFY_USER_AUTH_START = 'VERIFY_USER_AUTH_START'
export const VERIFY_USER_AUTH_SUCCESS = 'VERIFY_USER_AUTH_SUCCESS'
export const VERIFY_USER_AUTH_ERROR = 'VERIFY_USER_AUTH_ERROR'

// authorised or not
export const AUTHORISED = 'AUTHORISED';
export const NOT_AUTHORISED = 'NOT_AUTHORISED';